allowBuilds:
  '@fission-ai/openspec': true
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@ceynri/astro-toc-rail@0.1.0'
