name: Deploy Website

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Project install
        run: npm install
      - name: Project build
        run: npm run build
      - name: Project deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/srv/www/test/"
          # target: "/srv/www/ceynri.cn/"
