name: Deploy to GitHub Pages

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - feature/gh-pages

permissions:
  contents: write

env:
  NODE_VERSION: 14.21.3
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "docs: update content" || exit 0
          git push || exit 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
  
      - name: Project install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm run bootstrap
  
      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          publish_branch: gh-pages
